language: scala
before_install:
- openssl aes-256-cbc -K $encrypted_e4e35d0a3ab6_key -iv $encrypted_e4e35d0a3ab6_iv
  -in client.json.enc -out conf/client.json -d
- gem install sass
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  slack:
    secure: dKIXuycFCB3Qxo2tXAq/zoaYHg2uB2YlrJukXCOOgvTVwNlZVkEayOd1kraf6QX2PLIKu8Sp01FAJd5022GgFo6wiu72CkJBM5MeHZWyZGQuWKoVBU9mxVenNR9B84YkSRPlvCgjSsCKBEQ+u/lcFIHh62WaE8zrddGdNIchmV27XBy1N6zWGnpykU+bXD58BKtWyVfre4l3RZW2gG+xaVXSCfQXyNXTsBjP8BGCpCgfOLpay2DNujynK+l7Pwndci2BH20eJb/hmr4BgI2iiM2gyxfUjoqoaYDRB1vp+vUyn/VBNQPAOWejBg1e4KsU4dtyP6/iuDLO4ePlUMS2t7sgT6BH5qBOnPakqd3M9avsuR0JA4NSFMTj5MFhiOIipb5ujYzD8koHcsBcMKmwkkjOVeWZjS0bzsFzAmQDJhzB2Bq1C2r9z4jr41Q8JBeYqfE+pcFZjVB/gndsIGt00ORxrRaJ2lu5nlteiVQ/R11rXcC/AgScdgJ13CA5z0f7E0A7qypCpAotRaEf9e+yNlCkVzJgL9RMInHUY+65PsQLyI8z4elFKU9KhMof5kohgay7iizZAugHXh/b9JKonDOqimhtjzYCM7DvVL7vJ7ol/MEp5PrSMIhe4hBxeYnfWZYS+j4RsfpLIRf6a7dH6Se+dT2me07PuaKGNjwX+2Y=
