language: scala
before_install:
- openssl aes-256-cbc -K $encrypted_e4e35d0a3ab6_key -iv $encrypted_e4e35d0a3ab6_iv
  -in client.json.enc -out conf/client.json -d
- gem install sass -v 3.4.22
scala:
- 2.11.7
jdk:
- oraclejdk8
script:
- sbt test
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/
notifications:
  slack:
    secure: kn0M2xeMYrPL+8zey9ZZGlTlZ7mCITA03TTjUxHEBEBFuFn0dhRNyiSu+WdJJ0m8eXh77olACZWzo6p2XCdPObgzKqcKbKzPgKBIkMDOipPoguvQZ4yJO9l3xNA8cQVblvb1hAULjaT10DSSIoIrhbvuVhGqzS6b6YdWY5C0SyjEC0Axf4u+2b6TlAewLGwpRJ7j+KTmwKaN8DYExBcmptk3TkKCdsDLxZAPH2LuyZg5v1cVAUSbdbD02gxVg9FZ1x/BaiwsilvDTX3/4zKqW0BIFB/VPlRxYOcLc2jDoTkWFxDrLXH7imezZimdGkbvdmR/UjjhribSVQnaECCRIyidH+mNIqYI97kvx5cH8fTy7bnadbYwnVq5auXXxP9FIzMonBMlzUixN247G0KZuGMK07/Ol01D6wPuObv0c+4yw5wq0wOLLcN6nKqk8AuPm/Jl3fdicc+T0yOyf9X89B24bj3s5K1kfqpqtLI61YCSCyINMxFMJFrEX/7ld9X7gUWnZokkTvud+77io6uiA2LXbrclmn8PSs0QndtmNW+cPUQnbRjQhK5EulN8mFeUOFUtuHP31Na+/5+FpdyUnrHw4N9UCFNQwIiWH19oyG69qMl3SLrG0eW3fIJ/xW11qi6yo78S3XvFziTsusJxXh1k/NsMyCf2CyuLt08Ko0M=
